on:
  push:
    branches: [ main ]
    
jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Change dir
        run: cd backend

      - name: Build docker image & push to docker hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: shirobachi/musical-umbrella:latest
